name: Build and format

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build robot code
        run: ./gradlew build
  
  build:
    name: Format check
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Format check
        run: ./gradlew spotlessCheck
